package patients.model;
// Generated Jul 21, 2016 4:36:14 PM by Hibernate Tools 5.1.0.Beta1

/**
 * Insurance generated by hbm2java
 */
public class Insurance implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5050569841298863058L;
	
	private int healthInsuranceId;
	private Integer version;
	private String healthInsuranceType;
	private String healthInsuranceName;
	private Integer priceGroupId;
	private Integer iknumber;
	private String vknumber;
	private String shortNumber;
	private String validFrom;
	private String validTo;
	private String deductible;
	private String street;
	private String zipid;
	private String city;
	private String pobox;
	private String phone;
	private String fax;
	private String email;
	private String www;
	private String remark;
	private String insurancePayerId;
	private String selfCreated;
	private Integer deleted;

	public Insurance() {
	}

	public Insurance(int healthInsuranceId) {
		this.healthInsuranceId = healthInsuranceId;
	}

	public Insurance(int healthInsuranceId, String healthInsuranceType, String healthInsuranceName, Integer priceGroupId, Integer iknumber, String vknumber, String shortNumber, String validFrom, String validTo, String deductible,
			String street, String zipid, String city, String pobox, String phone, String fax, String email, String www, String remark, String insurancePayerId, String selfCreated, Integer deleted) {
		this.healthInsuranceId = healthInsuranceId;
		this.healthInsuranceType = healthInsuranceType;
		this.healthInsuranceName = healthInsuranceName;
		this.priceGroupId = priceGroupId;
		this.iknumber = iknumber;
		this.vknumber = vknumber;
		this.shortNumber = shortNumber;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.deductible = deductible;
		this.street = street;
		this.zipid = zipid;
		this.city = city;
		this.pobox = pobox;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.www = www;
		this.remark = remark;
		this.insurancePayerId = insurancePayerId;
		this.selfCreated = selfCreated;
		this.deleted = deleted;
	}

	public int getHealthInsuranceId() {
		return this.healthInsuranceId;
	}

	public void setHealthInsuranceId(int healthInsuranceId) {
		this.healthInsuranceId = healthInsuranceId;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getHealthInsuranceType() {
		return this.healthInsuranceType;
	}

	public void setHealthInsuranceType(String healthInsuranceType) {
		this.healthInsuranceType = healthInsuranceType;
	}

	public String getHealthInsuranceName() {
		return this.healthInsuranceName;
	}

	public void setHealthInsuranceName(String healthInsuranceName) {
		this.healthInsuranceName = healthInsuranceName;
	}

	public Integer getPriceGroupId() {
		return this.priceGroupId;
	}

	public void setPriceGroupId(Integer priceGroupId) {
		this.priceGroupId = priceGroupId;
	}

	public Integer getIknumber() {
		return this.iknumber;
	}

	public void setIknumber(Integer iknumber) {
		this.iknumber = iknumber;
	}

	public String getVknumber() {
		return this.vknumber;
	}

	public void setVknumber(String vknumber) {
		this.vknumber = vknumber;
	}

	public String getShortNumber() {
		return this.shortNumber;
	}

	public void setShortNumber(String shortNumber) {
		this.shortNumber = shortNumber;
	}

	public String getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(String validFrom) {
		this.validFrom = validFrom;
	}

	public String getValidTo() {
		return this.validTo;
	}

	public void setValidTo(String validTo) {
		this.validTo = validTo;
	}

	public String getDeductible() {
		return this.deductible;
	}

	public void setDeductible(String deductible) {
		this.deductible = deductible;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getZipid() {
		return this.zipid;
	}

	public void setZipid(String zipid) {
		this.zipid = zipid;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPobox() {
		return this.pobox;
	}

	public void setPobox(String pobox) {
		this.pobox = pobox;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWww() {
		return this.www;
	}

	public void setWww(String www) {
		this.www = www;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getInsurancePayerId() {
		return this.insurancePayerId;
	}

	public void setInsurancePayerId(String insurancePayerId) {
		this.insurancePayerId = insurancePayerId;
	}

	public String getSelfCreated() {
		return this.selfCreated;
	}

	public void setSelfCreated(String selfCreated) {
		this.selfCreated = selfCreated;
	}

	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

}
