package patients.model;
// Generated Jul 21, 2016 4:36:14 PM by Hibernate Tools 5.1.0.Beta1

import java.util.Date;

/**
 * Patients generated by hbm2java
 */
public class Patient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1909160219743863168L;
	
	private Integer internalNumber;
	private Integer version;
	private Integer patientId;
	private String patientType;
	private String sex;
	private String politeAddress;
	private String letterPoliteAddress;
	private String lastNamePrefix;
	private String title;
	private String firstName;
	private String lastName;
	private Date dateOfBirth;
	private String street;
	private String countryCode;
	private Integer zipid;
	private String city;
	private String homePhone;
	private String workPhone;
	private String mobilePhone;
	private String fax;
	private String email;
	private String www;
	private String staffId;
	private Integer doctorId;
	private Integer healthInsuranceId;
	private String healthInsuranceAccount;
	private String healthInsuranceStatus;
	private String statusExtension;
	private String cardValidTo;
	private String surchargeStatus;
	private String homepatient;
	private Integer distance;
	private String handlingType;
	private String altPayeeActive;
	private String appoliteAddress;
	private String apletterPoliteAddress;
	private String aplastNamePrefix;
	private String aptitle;
	private String aplastName;
	private String apfirstName;
	private String apstreet;
	private String apzip;
	private String apcity;
	private String profession;
	private String company;
	private String bankId;
	private String bankName;
	private String bankAccount;
	private String active;
	private Date recordCreationDate;
	private Date recordModificationDate;
	private String remark;
	private Integer deleted;
	private String extPatientId;
	private String iban;
	private String bic;

	public Patient() {
	}

	public Patient(Integer patientId, String patientType, String sex, String politeAddress, String letterPoliteAddress, String lastNamePrefix, String title, String firstName, String lastName, Date dateOfBirth, String street,
			String countryCode, Integer zipid, String city, String homePhone, String workPhone, String mobilePhone, String fax, String email, String www, String staffId, Integer doctorId, Integer healthInsuranceId,
			String healthInsuranceAccount, String healthInsuranceStatus, String statusExtension, String cardValidTo, String surchargeStatus, String homepatient, Integer distance, String handlingType, String altPayeeActive,
			String appoliteAddress, String apletterPoliteAddress, String aplastNamePrefix, String aptitle, String aplastName, String apfirstName, String apstreet, String apzip, String apcity, String profession, String company,
			String bankId, String bankName, String bankAccount, String active, Date recordCreationDate, Date recordModificationDate, String remark, Integer deleted, String extPatientId, String iban, String bic) {
		this.patientId = patientId;
		this.patientType = patientType;
		this.sex = sex;
		this.politeAddress = politeAddress;
		this.letterPoliteAddress = letterPoliteAddress;
		this.lastNamePrefix = lastNamePrefix;
		this.title = title;
		this.firstName = firstName;
		this.lastName = lastName;
		this.dateOfBirth = dateOfBirth;
		this.street = street;
		this.countryCode = countryCode;
		this.zipid = zipid;
		this.city = city;
		this.homePhone = homePhone;
		this.workPhone = workPhone;
		this.mobilePhone = mobilePhone;
		this.fax = fax;
		this.email = email;
		this.www = www;
		this.staffId = staffId;
		this.doctorId = doctorId;
		this.healthInsuranceId = healthInsuranceId;
		this.healthInsuranceAccount = healthInsuranceAccount;
		this.healthInsuranceStatus = healthInsuranceStatus;
		this.statusExtension = statusExtension;
		this.cardValidTo = cardValidTo;
		this.surchargeStatus = surchargeStatus;
		this.homepatient = homepatient;
		this.distance = distance;
		this.handlingType = handlingType;
		this.altPayeeActive = altPayeeActive;
		this.appoliteAddress = appoliteAddress;
		this.apletterPoliteAddress = apletterPoliteAddress;
		this.aplastNamePrefix = aplastNamePrefix;
		this.aptitle = aptitle;
		this.aplastName = aplastName;
		this.apfirstName = apfirstName;
		this.apstreet = apstreet;
		this.apzip = apzip;
		this.apcity = apcity;
		this.profession = profession;
		this.company = company;
		this.bankId = bankId;
		this.bankName = bankName;
		this.bankAccount = bankAccount;
		this.active = active;
		this.recordCreationDate = recordCreationDate;
		this.recordModificationDate = recordModificationDate;
		this.remark = remark;
		this.deleted = deleted;
		this.extPatientId = extPatientId;
		this.iban = iban;
		this.bic = bic;
	}

	public Integer getInternalNumber() {
		return this.internalNumber;
	}

	public void setInternalNumber(Integer internalNumber) {
		this.internalNumber = internalNumber;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Integer getPatientId() {
		return this.patientId;
	}

	public void setPatientId(Integer patientId) {
		this.patientId = patientId;
	}

	public String getPatientType() {
		return this.patientType;
	}

	public void setPatientType(String patientType) {
		this.patientType = patientType;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPoliteAddress() {
		return this.politeAddress;
	}

	public void setPoliteAddress(String politeAddress) {
		this.politeAddress = politeAddress;
	}

	public String getLetterPoliteAddress() {
		return this.letterPoliteAddress;
	}

	public void setLetterPoliteAddress(String letterPoliteAddress) {
		this.letterPoliteAddress = letterPoliteAddress;
	}

	public String getLastNamePrefix() {
		return this.lastNamePrefix;
	}

	public void setLastNamePrefix(String lastNamePrefix) {
		this.lastNamePrefix = lastNamePrefix;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	public Integer getZipid() {
		return this.zipid;
	}

	public void setZipid(Integer zipid) {
		this.zipid = zipid;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getHomePhone() {
		return this.homePhone;
	}

	public void setHomePhone(String homePhone) {
		this.homePhone = homePhone;
	}

	public String getWorkPhone() {
		return this.workPhone;
	}

	public void setWorkPhone(String workPhone) {
		this.workPhone = workPhone;
	}

	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWww() {
		return this.www;
	}

	public void setWww(String www) {
		this.www = www;
	}

	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	public Integer getHealthInsuranceId() {
		return this.healthInsuranceId;
	}

	public void setHealthInsuranceId(Integer healthInsuranceId) {
		this.healthInsuranceId = healthInsuranceId;
	}

	public String getHealthInsuranceAccount() {
		return this.healthInsuranceAccount;
	}

	public void setHealthInsuranceAccount(String healthInsuranceAccount) {
		this.healthInsuranceAccount = healthInsuranceAccount;
	}

	public String getHealthInsuranceStatus() {
		return this.healthInsuranceStatus;
	}

	public void setHealthInsuranceStatus(String healthInsuranceStatus) {
		this.healthInsuranceStatus = healthInsuranceStatus;
	}

	public String getStatusExtension() {
		return this.statusExtension;
	}

	public void setStatusExtension(String statusExtension) {
		this.statusExtension = statusExtension;
	}

	public String getCardValidTo() {
		return this.cardValidTo;
	}

	public void setCardValidTo(String cardValidTo) {
		this.cardValidTo = cardValidTo;
	}

	public String getSurchargeStatus() {
		return this.surchargeStatus;
	}

	public void setSurchargeStatus(String surchargeStatus) {
		this.surchargeStatus = surchargeStatus;
	}

	public String getHomepatient() {
		return this.homepatient;
	}

	public void setHomepatient(String homepatient) {
		this.homepatient = homepatient;
	}

	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	public String getHandlingType() {
		return this.handlingType;
	}

	public void setHandlingType(String handlingType) {
		this.handlingType = handlingType;
	}

	public String getAltPayeeActive() {
		return this.altPayeeActive;
	}

	public void setAltPayeeActive(String altPayeeActive) {
		this.altPayeeActive = altPayeeActive;
	}

	public String getAppoliteAddress() {
		return this.appoliteAddress;
	}

	public void setAppoliteAddress(String appoliteAddress) {
		this.appoliteAddress = appoliteAddress;
	}

	public String getApletterPoliteAddress() {
		return this.apletterPoliteAddress;
	}

	public void setApletterPoliteAddress(String apletterPoliteAddress) {
		this.apletterPoliteAddress = apletterPoliteAddress;
	}

	public String getAplastNamePrefix() {
		return this.aplastNamePrefix;
	}

	public void setAplastNamePrefix(String aplastNamePrefix) {
		this.aplastNamePrefix = aplastNamePrefix;
	}

	public String getAptitle() {
		return this.aptitle;
	}

	public void setAptitle(String aptitle) {
		this.aptitle = aptitle;
	}

	public String getAplastName() {
		return this.aplastName;
	}

	public void setAplastName(String aplastName) {
		this.aplastName = aplastName;
	}

	public String getApfirstName() {
		return this.apfirstName;
	}

	public void setApfirstName(String apfirstName) {
		this.apfirstName = apfirstName;
	}

	public String getApstreet() {
		return this.apstreet;
	}

	public void setApstreet(String apstreet) {
		this.apstreet = apstreet;
	}

	public String getApzip() {
		return this.apzip;
	}

	public void setApzip(String apzip) {
		this.apzip = apzip;
	}

	public String getApcity() {
		return this.apcity;
	}

	public void setApcity(String apcity) {
		this.apcity = apcity;
	}

	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getBankId() {
		return this.bankId;
	}

	public void setBankId(String bankId) {
		this.bankId = bankId;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankAccount() {
		return this.bankAccount;
	}

	public void setBankAccount(String bankAccount) {
		this.bankAccount = bankAccount;
	}

	public String getActive() {
		return this.active;
	}

	public void setActive(String active) {
		this.active = active;
	}

	public Date getRecordCreationDate() {
		return this.recordCreationDate;
	}

	public void setRecordCreationDate(Date recordCreationDate) {
		this.recordCreationDate = recordCreationDate;
	}

	public Date getRecordModificationDate() {
		return this.recordModificationDate;
	}

	public void setRecordModificationDate(Date recordModificationDate) {
		this.recordModificationDate = recordModificationDate;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	public String getExtPatientId() {
		return this.extPatientId;
	}

	public void setExtPatientId(String extPatientId) {
		this.extPatientId = extPatientId;
	}

	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public String getBic() {
		return this.bic;
	}

	public void setBic(String bic) {
		this.bic = bic;
	}

}
